apiVersion: v1
kind: Service
metadata:
  name: shop-backend-service
spec:
  type: ClusterIP
  selector:
    app: shop-backend-label
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: shop-frontend-service
spec:
  type: ClusterIP
  selector:
    app: shop-frontend-label
  ports:
  - port: 80
    targetPort: 80